# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StateOfChain' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StateOfChain

pod "CircleSlider"
pod "XJYChart"
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'web3swift', '~> 1.1.5'
end
